spring.profiles.include : auth

server:
  port: 9096
  servlet:
    context-path: /user
#server: #random port
#  port: 0

spring:
  application:
    name: user
  # Swagger 2.6.* 버전 이후 Path matching 에러 발생 - 해결법
  mvc:
    path match:
      matching-strategy: ant_path_matcher

# Eureka client 등록 (Naming server에 service 등록) - 추후 microservices 연결 시 변경 필요
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true    # client 등록 시, true로 세팅 - fetch(build) 될 때마다 새로 등록하여 사용
    register-with-eureka: true       # client 등록 시, true로 세팅
    service-url:
      defaultZone: ''

logging:
  level:
    com.fairytail: DEBUG
