# Application Auth 와 관련한 인증 정보가 들어감

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ''
            client-secret: ''
            redirect-uri: ''
            scope: profile, email

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ''
    username: ''
    password: ''

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true

# Token expiration 관련 설정
token:
  expiration_time: 86400000     # 토큰 유효기간 - 하루 (86400000 Milliseconds)
  secret: ''

